"""Run the sealed verifier on every cheat attempt and record the results.

Run from anywhere (after make_cheat_attempts.py):
    python authoring/provenance/check_cheat_attempts.py

For each authoring/evidence/cheat_attempts/*.json this runs
tests/test_submission.py exactly as tests/test.sh does (pytest + CTRF), applies
the same reward rule, and checks the failing tests equal EXPECTED in
make_cheat_attempts.py. Rewrites the table in cheat_attempts/README.md and
exits 1 if any attempt scores 1 or fails for an unexpected reason.
"""
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
CHEATS = ROOT/'authoring/evidence/cheat_attempts'
sys.path.insert(0, str(ROOT/'tests'))
from verifier.mesh_checks import load_submission, MeshValidationError  # noqa: E402
from verifier.fem_ref import solve  # noqa: E402
from verifier.error import energy_error  # noqa: E402

spec = importlib.util.spec_from_file_location('make_cheats', ROOT/'authoring/provenance/make_cheat_attempts.py')
make = importlib.util.module_from_spec(spec)
spec.loader.exec_module(make)


def run_verifier(path):
    """Return (reward, set of non-passing test names) using test.sh's rule."""
    with tempfile.TemporaryDirectory() as tmp:
        ctrf = Path(tmp)/'ctrf.json'
        env = dict(os.environ, SUBMISSION_PATH=str(path), PYTHONDONTWRITEBYTECODE='1')
        status = subprocess.run([sys.executable, '-m', 'pytest', 'test_submission.py', '-q',
                                 '-p', 'no:cacheprovider', '--ctrf', str(ctrf)],
                                cwd=ROOT/'tests', env=env, capture_output=True, text=True).returncode
        if not ctrf.exists():
            return 0, {'<pytest did not produce a CTRF report>'}
        results = json.loads(ctrf.read_text(encoding='utf-8'))['results']
    summary = results['summary']
    clean = all(summary.get(k, 0) == 0 for k in ('failed', 'skipped', 'pending', 'other'))
    reward = int(status == 0 and summary['tests'] > 0 and summary['passed'] == summary['tests'] and clean)
    failing = {t['name'].split('::')[-1] for t in results['tests'] if t['status'] != 'passed'}
    return reward, failing


def verifier_error(path):
    try:
        _, mesh = load_submission(path, max_vertices=40016)
    except MeshValidationError as exc:
        return f'invalid mesh: {exc}'
    return f'{energy_error(mesh, solve(mesh)).relative:.4f}'


def main():
    rows, ok = [], True
    for name in make.EXPECTED:
        path = CHEATS/f'{name}.json'
        data = json.loads(path.read_text(encoding='utf-8'))
        reward, failing = run_verifier(path)
        good = reward == 0 and failing == make.EXPECTED[name]
        ok &= good
        rows.append((name, data, reward, failing, verifier_error(path), good))
        print(f"{name:20s} reward {reward}  failing {sorted(failing)}  {'OK' if good else 'UNEXPECTED'}", flush=True)

    lines = ['# Cheat attempts', '',
             'Each submission below must score 0. Generated by',
             '`authoring/provenance/make_cheat_attempts.py`; checked against the sealed verifier',
             '(`tests/test_submission.py`, same reward rule as `tests/test.sh`) by',
             '`authoring/provenance/check_cheat_attempts.py`. Apart from `fake_error.json`, each',
             'file reports its DOF and true error honestly, so it fails only for its intended reason.', '',
             '| File | What it is | DOF | Reported error | Verifier result | Failing tests | Reward |',
             '|---|---|---:|---:|---|---|---:|']
    for name, data, reward, failing, err, good in rows:
        lines.append(f"| `{name}.json` | {make.WHY[name]} | {data['dof']} | {data['reported_error']:.4f} | "
                     f"{err} | {', '.join(f'`{t}`' for t in sorted(failing))} | {reward} |")
    lines += ['', f'Limits: error ≤ 0.05, DOF ≤ {make.BUDGET}, history ≤ 54 records.',
              'All attempts scored 0 for the expected reasons.' if ok else
              '**CHECK FAILED: an attempt scored 1 or failed for an unexpected reason.**', '']
    (CHEATS/'README.md').write_text('\n'.join(lines), encoding='utf-8')
    return 0 if ok else 1


if __name__ == '__main__':
    raise SystemExit(main())
