"""Oracle and nop runs with plain Docker, following the Harbor flow (TODO 3.5/3.6).

Run from anywhere (Docker required): python authoring/provenance/check_oracle_nop.py
Writes authoring/evidence/oracle_run.md and nop_run.md; exits 1 unless the
oracle scores 1 and the nop run scores 0.

Steps mirror Harbor: build environment/Dockerfile and tests/Dockerfile; run
the environment container with task.toml's cpus/memory (oracle: solution/
mounted and solve.sh executed; nop: nothing executed); copy out the artifact
/app/output/submission.json; run tests/test.sh in the verifier container
(no network) with the artifact mounted at the same path; read reward.txt.
"""
import json
from pathlib import Path
import platform
import subprocess
import tempfile
import time
import tomllib

ROOT = Path(__file__).resolve().parents[2]
TOML = tomllib.loads((ROOT/'task.toml').read_text(encoding='utf-8'))
ENV, VERIFY = 'afem-env:oracle-nop', 'afem-verifier:oracle-nop'
LIMITS = ['--cpus', str(TOML['environment']['cpus']), '--memory', f"{TOML['environment']['memory_mb']}m"]


def docker(*args, check=True):
    return subprocess.run(['docker', *args], capture_output=True, text=True, check=check)


def run(kind, work):
    out, logs = work/f'{kind}_output', work/f'{kind}_logs'
    out.mkdir()
    logs.mkdir()
    command = ['bash', '/solution/solve.sh'] if kind == 'oracle' else ['true']
    mounts = ['-v', f'{ROOT/"solution"}:/solution:ro'] if kind == 'oracle' else []
    start = time.perf_counter()
    agent = docker('run', '--rm', *LIMITS, *mounts, '-v', f'{out}:/app/output', ENV, *command, check=False)
    agent_seconds = time.perf_counter() - start
    artifact = out/'submission.json'
    artifact_mount = ['-v', f'{artifact}:/app/output/submission.json:ro'] if artifact.exists() else []
    start = time.perf_counter()
    verifier = docker('run', '--rm', *LIMITS, '--network', 'none', *artifact_mount,
                      '-v', f'{logs}:/logs/verifier', VERIFY, 'bash', '/tests/test.sh', check=False)
    verify_seconds = time.perf_counter() - start
    reward = (logs/'reward.txt').read_text(encoding='utf-8')
    summary = json.loads((logs/'ctrf.json').read_text(encoding='utf-8'))['results']['summary'] \
        if (logs/'ctrf.json').exists() else None
    submission = json.loads(artifact.read_text(encoding='utf-8')) if artifact.exists() else None
    return dict(agent_exit=agent.returncode, agent_seconds=agent_seconds, agent_tail=agent.stdout.strip().splitlines()[-2:],
                artifact=artifact.exists(), submission=submission, reward=reward,
                verify_seconds=verify_seconds, summary=summary)


def write(kind, r, expected, docker_version):
    s = r['summary']
    lines = [f'# {kind.capitalize()} run', '',
             'Generated by `authoring/provenance/check_oracle_nop.py`: the Harbor flow reproduced with',
             f'plain Docker ({docker_version}, host {platform.system()}), with task.toml resources',
             f'(`{" ".join(LIMITS)}`; verifier also `--network none`).', '',
             '| Step | Result |', '|---|---|',
             f'| Environment container | {"`bash /solution/solve.sh`" if kind == "oracle" else "nothing executed"}: '
             f'exit {r["agent_exit"]}, {r["agent_seconds"]:.0f} s |',
             f'| Artifact `/app/output/submission.json` | {"present" if r["artifact"] else "absent"} |']
    if r['submission']:
        sub = r['submission']
        lines.append(f'| Submission | {len(sub["vertices"])} vertices, {len(sub["triangles"])} triangles, '
                     f'DOF {sub["dof"]}, reported error {sub["reported_error"]:.10f}, {len(sub["history"])} history records |')
    lines += [f'| Verifier `tests/test.sh` | {r["verify_seconds"]:.0f} s; CTRF summary '
              f'{ {k: s[k] for k in ("tests", "passed", "failed", "skipped")} if s else "none (pytest did not run tests)"} |',
              f'| **Reward** | **{r["reward"]}** (required: {expected}) |', '']
    if kind == 'oracle' and r['agent_tail']:
        lines += ['Last lines of the solver log:', '', '```', *r['agent_tail'], '```', '']
    lines += ['Still to do: repeat under Harbor itself (`harbor` CLI not available on the authoring machine).', '']
    (ROOT/f'authoring/evidence/{kind}_run.md').write_text('\n'.join(lines), encoding='utf-8')


def main():
    docker_version = docker('version', '--format', 'engine {{.Server.Version}}').stdout.strip()
    docker('build', '-q', '-t', ENV, str(ROOT/'environment'))
    docker('build', '-q', '-t', VERIFY, str(ROOT/'tests'))
    ok = True
    with tempfile.TemporaryDirectory(dir=ROOT/'authoring') as tmp:
        for kind, expected in (('oracle', '1'), ('nop', '0')):
            r = run(kind, Path(tmp))
            write(kind, r, expected, docker_version)
            ok &= r['reward'] == expected
            print(f"{kind}: reward {r['reward']} (expected {expected}); environment {r['agent_seconds']:.0f} s, "
                  f"verifier {r['verify_seconds']:.0f} s", flush=True)
    return 0 if ok else 1


if __name__ == '__main__':
    raise SystemExit(main())
