"""Oracle and nop runs with plain Docker, following the Harbor flow (TODO 3.5/3.6).

Run from anywhere (Docker required): python authoring/provenance/check_oracle_nop.py
Writes authoring/evidence/oracle_run.md and nop_run.md; exits 1 unless the
oracle scores 1 and the nop run scores 0.

Steps mirror Harbor: build environment/Dockerfile and tests/Dockerfile; run
the environment container with task.toml's cpus/memory (oracle: solution/
mounted and solve.sh executed; nop: nothing executed); copy out the artifact
/app/output/submission.json; run tests/test.sh in the verifier container
(no network) with the artifact mounted at the same path; read reward.txt.
"""
import argparse
import json
import os
import re
import shutil
from pathlib import Path
import platform
import subprocess
import tempfile
import time
import tomllib

ROOT = Path(__file__).resolve().parents[2]
TOML = tomllib.loads((ROOT/'task.toml').read_text(encoding='utf-8'))
ENV, VERIFY = 'afem-env:oracle-nop', 'afem-verifier:oracle-nop'
LIMITS = ['--cpus', str(TOML['environment']['cpus']), '--memory', f"{TOML['environment']['memory_mb']}m"]


def docker(*args, check=True):
    return subprocess.run(['docker', *args], capture_output=True, text=True, check=check)


def run(kind, work):
    out, logs = work/f'{kind}_output', work/f'{kind}_logs'
    out.mkdir()
    logs.mkdir()
    command = ['bash', '/solution/solve.sh'] if kind == 'oracle' else ['true']
    mounts = ['-v', f'{ROOT/"solution"}:/solution:ro'] if kind == 'oracle' else []
    start = time.perf_counter()
    agent = docker('run', '--rm', *LIMITS, *mounts, '-v', f'{out}:/app/output', ENV, *command, check=False)
    agent_seconds = time.perf_counter() - start
    artifact = out/'submission.json'
    artifact_mount = ['-v', f'{artifact}:/app/output/submission.json:ro'] if artifact.exists() else []
    start = time.perf_counter()
    verifier = docker('run', '--rm', *LIMITS, '--network', 'none', *artifact_mount,
                      '-v', f'{logs}:/logs/verifier', VERIFY, 'bash', '/tests/test.sh', check=False)
    verify_seconds = time.perf_counter() - start
    reward = (logs/'reward.txt').read_text(encoding='utf-8')
    summary = json.loads((logs/'ctrf.json').read_text(encoding='utf-8'))['results']['summary'] \
        if (logs/'ctrf.json').exists() else None
    submission = json.loads(artifact.read_text(encoding='utf-8')) if artifact.exists() else None
    return dict(agent_exit=agent.returncode, agent_seconds=agent_seconds, agent_tail=agent.stdout.strip().splitlines()[-2:],
                artifact=artifact.exists(), submission=submission, reward=reward,
                verify_seconds=verify_seconds, summary=summary)


def run_harbor(harbor, kind, jobs_dir):
    """Run `harbor run -p <task> -a <kind> -e docker`; return (reward, runtime) or None."""
    start = time.perf_counter()
    out = subprocess.run([harbor, 'run', '-p', str(ROOT), '-a', kind, '-e', 'docker', '-o', str(jobs_dir)],
                         capture_output=True, text=True, encoding='utf-8', errors='replace',
                         env=dict(os.environ, PYTHONIOENCODING='utf-8'))
    mean = re.findall(r'Mean:\s*([0-9.]+)', out.stdout)
    return (mean[-1], time.perf_counter() - start) if out.returncode == 0 and mean else None


def harbor_version(harbor):
    return subprocess.run([harbor, '--version'], capture_output=True, text=True).stdout.strip()


def write(kind, r, expected, docker_version, harbor=None):
    s = r['summary']
    lines = [f'# {kind.capitalize()} run', '',
             'Generated by `authoring/provenance/check_oracle_nop.py`: the Harbor flow reproduced with',
             f'plain Docker ({docker_version}, host {platform.system()}), with task.toml resources',
             f'(`{" ".join(LIMITS)}`; verifier also `--network none`).', '',
             '| Step | Result |', '|---|---|',
             f'| Environment container | {"`bash /solution/solve.sh`" if kind == "oracle" else "nothing executed"}: '
             f'exit {r["agent_exit"]}, {r["agent_seconds"]:.0f} s |',
             f'| Artifact `/app/output/submission.json` | {"present" if r["artifact"] else "absent"} |']
    if r['submission']:
        sub = r['submission']
        lines.append(f'| Submission | {len(sub["vertices"])} vertices, {len(sub["triangles"])} triangles, '
                     f'DOF {sub["dof"]}, reported error {sub["reported_error"]:.10f}, {len(sub["history"])} history records |')
    lines += [f'| Verifier `tests/test.sh` | {r["verify_seconds"]:.0f} s; CTRF summary '
              f'{ {k: s[k] for k in ("tests", "passed", "failed", "skipped")} if s else "none (pytest did not run tests)"} |',
              f'| **Reward** | **{r["reward"]}** (required: {expected}) |', '']
    if kind == 'oracle' and r['agent_tail']:
        lines += ['Last lines of the solver log:', '', '```', *r['agent_tail'], '```', '']
    if harbor:
        version, result = harbor
        lines += [f'Harbor {version}: `harbor run -p . -a {kind} -e docker` → '
                  + (f'**reward {float(result[0]):g}** ({result[1]:.0f} s).' if result else '**run failed**.'), '']
    else:
        lines += ['Harbor run not included (pass --harbor PATH or put `harbor` on PATH).', '']
    (ROOT/f'authoring/evidence/{kind}_run.md').write_text('\n'.join(lines), encoding='utf-8')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--harbor', default=shutil.which('harbor'), help='harbor executable (default: on PATH)')
    args = parser.parse_args(argv)
    docker_version = docker('version', '--format', 'engine {{.Server.Version}}').stdout.strip()
    docker('build', '-q', '-t', ENV, str(ROOT/'environment'))
    docker('build', '-q', '-t', VERIFY, str(ROOT/'tests'))
    ok = True
    with tempfile.TemporaryDirectory(dir=ROOT/'authoring') as tmp:
        for kind, expected in (('oracle', '1'), ('nop', '0')):
            r = run(kind, Path(tmp))
            harbor = None
            if args.harbor:
                result = run_harbor(args.harbor, kind, Path(tmp)/'harbor-jobs')
                harbor = (harbor_version(args.harbor), result)
                ok &= result is not None and float(result[0]) == float(expected)
                print(f"{kind}: harbor {'reward ' + result[0] if result else 'FAILED'}", flush=True)
            write(kind, r, expected, docker_version, harbor)
            ok &= r['reward'] == expected
            print(f"{kind}: reward {r['reward']} (expected {expected}); environment {r['agent_seconds']:.0f} s, "
                  f"verifier {r['verify_seconds']:.0f} s", flush=True)
    return 0 if ok else 1


if __name__ == '__main__':
    raise SystemExit(main())
